#!/usr/bin/env node
/**
 * api-docs - Generate API documentation from FastAPI/Flask endpoints
 *
 * Auto-generated by QuantumLogic derive-macros
 * Based on detected patterns in: rvc
 */


const ql = require('../quantum-logic');

// Find all HTTP endpoints
const decorates = ql.atom('decorates', 'rvc');
const endpoints = decorates.filter(d =>
    d.args[1].match(/^(app|router)\.(get|post|put|delete|patch)$/)
);

console.log('# API Endpoints\n');
for (const ep of endpoints) {
    const method = ep.args[1].split('.')[1].toUpperCase();
    console.log(`## ${method} /${ep.args[2]}`);
    console.log(`Handler: ${ep.args[2]} (${ep.args[0]}:${ep.args[3]})`);
    console.log();
}

