#!/usr/bin/env node
/**
 * grpc-audit - Audit gRPC services, methods, and client usage
 *
 * Auto-generated by QuantumLogic derive-macros
 * Based on detected patterns in: rvc
 */


const ql = require('../quantum-logic');

// Find all gRPC servicers
const inherits = ql.atom('inherits', 'rvc');
const servicers = inherits.filter(i => i.args[2].includes('Servicer'));

// Find servicer methods
const defines = ql.atom('defines', 'rvc');
for (const svc of servicers) {
    const methods = defines.filter(d =>
        d.args[1].startsWith(svc.args[1] + '.') &&
        d.args[2] === 'method'
    );
    console.log(`\n${svc.args[1]} (${svc.args[0]})`);
    methods.forEach(m => console.log(`  - ${m.args[1].split('.')[1]}`));
}

