#!/usr/bin/env node
/**
 * model-audit - Audit ML model usage, Triton clients, and inference calls
 *
 * Auto-generated by QuantumLogic derive-macros
 * Based on detected patterns in: rvc
 */


const ql = require('../quantum-logic');

// Find Triton client usage
const imports = ql.atom('imports', 'rvc');
const calls = ql.atom('calls', 'rvc');

const tritonClients = imports.filter(i => i.args[1].includes('triton'));
const inferenceCalls = calls.filter(c =>
    c.args[2].includes('infer') || c.args[2].includes('predict')
);

console.log('Triton Client Locations:');
tritonClients.forEach(t => console.log(`  ${t.args[0]}`));

console.log('\nInference Calls:');
inferenceCalls.forEach(c => console.log(`  ${c.args[0]}:${c.args[3]} - ${c.args[2]}`));

