#!/usr/bin/env node
/**
 * resource-audit - Audit context managers and resource lifecycle
 *
 * Auto-generated by QuantumLogic derive-macros
 * Based on detected patterns in: rvc
 */


const ql = require('../quantum-logic');

// Find context managers
const defines = ql.atom('defines', 'rvc');

const enters = defines.filter(d => d.args[1].includes('__enter__'));
const exits = defines.filter(d => d.args[1].includes('__exit__'));

console.log('Context Managers:\n');
enters.forEach(e => {
    const cls = e.args[1].split('.')[0];
    console.log(`${cls} (${e.args[0]})`);

    // Check if properly paired
    const hasExit = exits.some(x => x.args[1].startsWith(cls + '.'));
    if (!hasExit) {
        console.log(`  ⚠️  Missing __exit__!`);
    }
});

