#!/usr/bin/env node
/**
 * worker-audit - Audit multiprocessing workers, queues, and job flow
 *
 * Auto-generated by QuantumLogic derive-macros
 * Based on detected patterns in: rvc
 */


const ql = require('../quantum-logic');

// Find worker/queue patterns
const imports = ql.atom('imports', 'rvc');
const defines = ql.atom('defines', 'rvc');
const calls = ql.atom('calls', 'rvc');

// Queue usage
const queueCalls = calls.filter(c =>
    c.args[2].includes('.put') || c.args[2].includes('.get')
);

// Worker functions
const workerFuncs = defines.filter(d =>
    d.args[1].toLowerCase().includes('worker')
);

console.log('Worker Functions:');
workerFuncs.forEach(w => console.log(`  ${w.args[1]} (${w.args[0]})`));

console.log('\nQueue Operations:');
const byFile = {};
queueCalls.forEach(c => {
    if (!byFile[c.args[0]]) byFile[c.args[0]] = [];
    byFile[c.args[0]].push(c);
});
Object.entries(byFile).forEach(([file, ops]) => {
    console.log(`  ${file}: ${ops.length} queue ops`);
});

